services:
  nginx:
    container_name: nginx
    # restart: always
    image: nginx:1.20
    ports:
      - 8081:80
    volumes:
      - ./htmls/:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf